name: alphonsa_travels
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.0
  flutter_launcher_icons: ^0.10.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/homepage/

flutter_launcher_icons:
  android: true
  ios: true
  min_sdk_android: 21 
  image_path: "assets/images/homepage/logo.png"
  adaptive_icon_background: "#FFFFFF"  
  adaptive_icon_foreground: "assets/images/homepage/logo.png"
